/*
Nathanael Obrey
11/14/2025
CPSC-39 Final Project
*/

/*
Code Structure was generated through the use of GPT-5 from OpenAI which I accessed through copilot.

CSV Files were generated through an algorithm that I prompeted GPT-5 to create sample data for testing purposes.

All other logic and other implementation was either written by me (Nathanael Obrey) or assisted through small snippets generated by GPT-5.

Every use of AI was prompted in a way to ensure that the final code met my requirements and was reviewed and modified by me to ensure correctness and adherence to project specifications.

Using AI assistance is allowed for this project as per the guidelines provided by the instructor.
*/

import java.util.*;

public class BusinessApp {
    public static void main(String[] args) throws Exception {
        // load data from CSV files - HashMap for fast lookup by customerID (O(1) average time) - sends
        Map<Integer, Customer> customers = DataLoader.loadCustomers("customers.csv");
        DataLoader.loadPurchases("purchases.csv", customers);

        Scanner sc = new Scanner(System.in); // scanner for user input
        int choice; // integer used for menu choice

        //execute the following code, until the user decides to exit
        do {
            //display menu in terminal
            System.out.println("\n=== Business App Menu ===");
            System.out.println("1. Add Customer");
            System.out.println("2. Delete Customer");
            System.out.println("3. Search Customer by ID");
            System.out.println("4. List All Customers");
            System.out.println("5. Add Transaction");
            System.out.println("6. View Purchase History");
            System.out.println("7. Exit");
            
            //Prompt user for choice
            System.out.print("Enter choice: ");
            choice = sc.nextInt();
            sc.nextLine(); // consume newline

            switch (choice) {
                case 1:
                    addCustomer(sc, customers);
                    break;
                case 2:
                    deleteCustomer(sc, customers);
                    break;
                case 3:
                    searchCustomer(sc, customers);
                    break;
                case 4:
                    listCustomers(customers);
                    break;
                case 5:
                    addTransaction(sc, customers);
                    break;
                case 6:
                    viewPurchases(sc, customers);
                    break;
                case 7:
                    System.out.print("Are you sure you want to exit? (Y/N): "); // confirm exit
                    String confirm = sc.nextLine().trim().toLowerCase(); // get user input and ignore case
                    if (confirm.equals("y") || confirm.equals("yes")) {
                        System.out.println("Goodbye!");
                        // leave choice as 7 so the loop will exit
                    } else {
                        // set to a non-exit value so the loop continues
                        choice = 0;
                    }
                    break;
                default:
                    System.out.println("Invalid choice.");
            } // end switch
        } while (choice != 7);
    }

    // Add a new customer
    private static void addCustomer(Scanner sc, Map<Integer, Customer> customers) {
        System.out.print("Enter 5-digit Customer ID: ");
        int id = sc.nextInt(); sc.nextLine();
        System.out.print("Enter Last Name: ");
        String lastName = sc.nextLine();
        System.out.print("Enter First Name: ");
        String firstName = sc.nextLine();
        System.out.print("Enter Phone: ");
        String phone = sc.nextLine();

        Customer c = new Customer(id, lastName, firstName, phone);
        customers.put(id, c);
        System.out.println("Customer added!");
        // Auto-save directly to CSV file after adding customer - bypass setters 
        saveData(customers);
    } // end addCustomer

    // Delete a customer by ID
    private static void deleteCustomer(Scanner sc, Map<Integer, Customer> customers) {
        System.out.print("Enter Customer ID to delete: ");
        int id = sc.nextInt();
        sc.nextLine(); // consume newline
        Customer c = customers.get(id); // lookup customer by ID - O(1) average time because of HashMap
        if (c != null) { // if customer exists
            System.out.print("Are you sure you want to delete " + c.getFirstName() + " " + c.getLastName() + " (ID: " + id + ")? (Y/N): ");
            String confirm = sc.nextLine().trim().toLowerCase();
            if (confirm.equals("y") || confirm.equals("yes")) {
                customers.remove(id);
                System.out.println("Customer deleted.");
                // Auto-save directly to CSV file after deleting customer - bypass setters 
                saveData(customers);
            } else {
                System.out.println("Deletion cancelled.");
            }
        } else { // if customer does not exist
            System.out.println("Customer not found.");
        }
    } // end deleteCustomer

    // Search for a customer by ID
    private static void searchCustomer(Scanner sc, Map<Integer, Customer> customers) {
        System.out.print("Enter Customer ID: ");
        int id = sc.nextInt();
        Customer c = customers.get(id);
        if (c != null) { // if customer exists
            System.out.println("Found: " + c.getFirstName() + " " + c.getLastName() + " (" + c.getPhone() + ")"); // display customer info
        } else { // if customer does not exist
            System.out.println("Customer not found.");
        }
    } // end searchCustomer

    // List all customers
    private static void listCustomers(Map<Integer, Customer> customers) {
        for (Customer c : customers.values()) { // iterate through all customers - O(n)
            System.out.println(c.getCustomerID() + " - " + c.getFirstName() + " " + c.getLastName());
        }
    } // end listCustomers

    // View purchase history for a customer, with running total via recursion
    private static void viewPurchases(Scanner sc, Map<Integer, Customer> customers) {
        System.out.print("Enter Customer ID: ");
        int id = sc.nextInt();
        Customer c = customers.get(id);
        if (c != null) {
            System.out.println("Purchase History for " + c.getFirstName() + " " + c.getLastName() + ":");
            for (Purchase p : c.getPurchases()) {
                System.out.println(" - " + p.getProductName() + " ($" + p.getPrice() + ")");
            }
            // Compute and print running total using recursion
            double total = runningTotal(c.getPurchases(), 0);
            System.out.printf("Total: $%.2f\n", total);
        } else {
            System.out.println("Customer not found.");
        }
    } // end viewPurchases

    // Recursive helper that returns the sum of prices from index `idx` to end
    private static double runningTotal(List<Purchase> list, int idx) {
        if (list == null || idx >= list.size()) return 0.0;
        Purchase p = list.get(idx);
        return p.getPrice() + runningTotal(list, idx + 1);
    } // end runningTotal

    // Add a transaction for a customer
    private static void addTransaction(Scanner sc, Map<Integer, Customer> customers) {
        System.out.print("Enter Customer ID: ");
        int id = sc.nextInt(); sc.nextLine();
        Customer c = customers.get(id);
        if (c != null) {
            System.out.print("Enter product name: ");
            String product = sc.nextLine();
            System.out.print("Enter price: ");
            double price = sc.nextDouble(); sc.nextLine();
            c.addPurchase(new Purchase(product, price));
            System.out.println("Transaction added: " + product + " ($" + price + ")");
            // Build printable receipt for this transaction - LinkedList for easy line-by-line storage (O(n))
            LinkedList<String> receipt = new LinkedList<>();
            String timestamp = java.time.LocalDateTime.now().toString();
            receipt.add("=== BusinessApp Receipt ===");
            receipt.add("Timestamp: " + timestamp);
            receipt.add("Customer: " + c.getFirstName() + " " + c.getLastName() + " (ID: " + c.getCustomerID() + ")");
            receipt.add("");
            receipt.add("Items:");
            receipt.add(product + " - $" + String.format("%.2f", price));
            
            // apply optional discount (Why did I add this? idk but it's here now)
            double discount = 0.0;
            System.out.print("Apply discount? (Y/N): ");
            String discChoice = sc.nextLine().trim().toLowerCase();
            if (discChoice.equals("y") || discChoice.equals("yes")) {
                System.out.print("Enter discount amount (dollars): ");
                try {
                    discount = sc.nextDouble(); sc.nextLine();
                    receipt.add("Discount: -$" + String.format("%.2f", discount));
                } catch (Exception e) {
                    sc.nextLine(); // consume bad input
                    System.out.println("Invalid discount, continuing without discount.");
                    discount = 0.0;
                }
            }
            // calculate total after discount
            double total = price - discount;
            if (total < 0) total = 0;
            receipt.add("");
            receipt.add("Total: $" + String.format("%.2f", total));
            receipt.add("=== Thank you ===");

            // Print receipt to console
            printReceipt(receipt);

            // Auto-save customers/purchases (do NOT save receipts to CSV)
            saveData(customers);
        } else {
            System.out.println("Customer not found.");
        }
    } // end addTransaction

    // Print receipt line-by-line to console - was going to eventually save to file that could be printed, but not implemented
    private static void printReceipt(LinkedList<String> receipt) {
        for (String line : receipt) {
            System.out.println(line);
        }
    } // end printReceipt

    // Save customers and purchases to CSV files (outdated method, now called directly in add/delete/transaction methods)
    // keep this in case I want to batch save later
    private static void saveData(Map<Integer, Customer> customers) {
        try {
            DataLoader.saveCustomers("customers.csv", customers.values());
            DataLoader.savePurchases("purchases.csv", customers.values());
            System.out.println("Data saved to customers.csv and purchases.csv");
        } catch (java.io.IOException e) {
            System.out.println("Error saving data: " + e.getMessage());
        }
    } // end saveData
} // end BusinessApp class
